# This is a streamlined cloudbuild.yaml that leverages a multi-stage Dockerfile.
# The Dockerfile now handles all dependency installation, linting, and testing.

steps:
# 1. Build the container image using the multi-stage Dockerfile.
# The 'builder' stage will run linting and tests. If they fail, this step fails.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA', '.']
  id: 'Build'

# 2. Push the final container image to Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA']
  id: 'Push'
  waitFor: ['Build']

# 3. Deploy the container image to Cloud Run.
- name: 'gcr.io/google-appengine/exec-wrapper'
  args:
  - '-i'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'
  - '--'
  - 'gcloud'
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--service-account' # Added service account flag
  - 'firebase-ci-cd-sa@soy-comm-2024.iam.gserviceaccount.com' # Your service account email
  id: 'Deploy Backend'
  waitFor: ['Push']

# 4. Deploy to Firebase Hosting.
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'npm install -g firebase-tools && firebase deploy --only hosting --project $PROJECT_ID --non-interactive --token $$FIREBASE_TOKEN'
  secretEnv: ['FIREBASE_TOKEN']
  id: 'Deploy Frontend'

# List of images to be built and pushed.
images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'

# Use Secret Manager for the Firebase token.
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/firebase-ci-token/versions/latest
    env: 'FIREBASE_TOKEN'

# Explicitly set the logging option to resolve the service account permissions error.
options:
  logging: CLOUD_LOGGING_ONLY

# Default values for substitutions. Can be overridden in your trigger.
substitutions:
  _SERVICE_NAME: soy-intel-svc
  _REGION: us-central1
  _REPO_NAME: soy-intel-repository
