substitutions:
  _REGION: "us-central1"
  _REPO: "containers"
  _SERVICE: "api-core"
  _RUNTIME_SA: "run-runtime@$_PROJECT_ID.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build","-t","us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}","-f","Dockerfile","."]

  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push","us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}",
        "--region","${_REGION}",
        "--platform","managed",
        "--service-account","${_RUNTIME_SA}",
        "--allow-unauthenticated=false",
        "--min-instances","1"
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${SHORT_SHA}"